#
# remove the virtual machine
- hosts: builder
  become: yes
  gather_facts: no

  tasks:  

    # "subscription-manager repos --enable ansible-automation-platform-2.2-for-rhel-8-x86_64-rpms"
  
  - name: enable repo
    #ansible.builtin.command: 
      #cmd: "subscription-manager repos --enable ansible-automation-platform-2.2-for-rhel-8-x86_64-rpms"
    rhsm_repository:
      name: ansible-automation-platform-2.2-for-rhel-8-x86_64-rpms
      state: enabled

  - name: install packages
    ansible.builtin.dnf: 
      name: 
      - ansible-core 
      - ansible-navigator 
      - ansible-builder
      state: latest

