---
- name: build new machine
  hosts: builder
  become: yes
  gather_facts: no
  serial: 1
  #vars_files:
  #- vault.yml

  roles: 
  - role: libvirt-guest
    delegate_to: host2.lab.example.com

  tasks:
  - name: Wait for new server to be ready
    ansible.builtin.wait_for_connection:
      timeout: 30
    become: no

