- name: install the foundation
  hosts: builder
  become: yes
  serial: 1
  gather_facts: no
  # override user password for privilege escalation.
  # ansible already has a become password
  # this new host has a different become password.
  # By the time the role is finished, user has passwordless sudo and this is no longer needed.
  roles:
    - ansible-target
# what other prereqs? 

  tasks:

  - name: check with ping
    ping:

  # make sure the new machine has been rebooted before upgrading all packages
  # If kickstart failed to register with RHSM, this module does nothing.
  - name: Upgrade all packages
    ansible.builtin.dnf:
      name: "*"
      state: latest
    register: r_dnf

  - debug:
      var: r_dnf

  - name: can the OS survive another reboot? 
    ansible.builtin.reboot:
    when: r_dnf['changed'] == true

  - name: can we ping the host after the reboot?
    ansible.builtin.wait_for_connection:
      timeout: 30


# network manager
  - name: use name1 for DNS
    ansible.builtin.command:
      cmd: "{{ item }}"
    loop:
      - nmcli con mod enp1s0 ipv4.dns 192.168.1.12
      - nmcli con mod enp1s0 ipv4.ignore-auto-dns yes
      - nmcli con up enp1s0


# firewall
  - name: permit traffic in default zone
    ansible.posix.firewalld:
      service: "{{ item }}"
      immediate: yes
      permanent: yes
      state: enabled
    loop:
      - cockpit
      - http
      - https
      - ssh

# systemd
  - name: start the server
    ansible.builtin.systemd:
      name: cockpit.socket
      state: started
      enabled: yes

#
# checks

- name: create a server certificate
  ansible.builtin.import_playbook: cert-server.yml

# somehow get a copy of the boot ISO onto builder1.
#  scp host1.lab.example.com:/var/lib/libvirt/images/rhel-8.6-x86_64-boot.iso builder1.lab.example.com:/var/tmp/


