- name: image builder service
  hosts: builder
  become: yes
  gather_facts: no
  tasks: 

  # !!! some duplicated in group_vars/builder/main.yml
  # package 'lorax' provides command 'mkksiso'
  # package 'weldr-client' provides command 'composer-cli'
  - name: install image builder packages
    ansible.builtin.dnf:
      name: 
        - cockpit-composer
        - git
        - lorax
        - osbuild-composer
        - weldr-client
      state: latest
    register: r_dnf_builder

  - name: start the server
    ansible.builtin.systemd:
      name: osbuild-composer.socket
      state: started
      enabled: yes


# shenanigans to get ISO from hypervisor to builder
  - name: .ssh directory
    ansible.builtin.file:
      path: /root/.ssh
      state: directory
      mode: '0700'

  - name: authorized_keys file
    ansible.builtin.copy:
      dest: /root/.ssh/authorized_keys
      content: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCqoNhX7+mzhU9pEnor291D2MNvCxT2Ee6N0clKTdR8UpZbf2j0Eb9sBtxy9opVgu38tnG/3lQj0ha94Q1mJOI+puaRfZEP17u2C5rMdAkF4Fn7ipOmlTR/QIdhYAJOf7sVk5ftCz9DYBonE/JLCX+cutJ9VuKgZMQx9/NsG9kr/kRl9o/2WOaUKdFSOJaHZYv/nTIfMprca6GJUvJkdwG6BYAcDMeDFiLYpcB/JwRO0ZgsQWSTJpHfcz8WqarwVr8zNOmTBPO8bC5nJugiCc4/LVZVa5QvD4GlMNHNuwkbbf+B6h2MYSMMankAR0DlZ5WQbY14ja2fWGL1+qzNTuWldLIpsQk/1OW4beIF924V0nNJm6UGZtZJ4iiecRmKeOQgW/D6pEdAEy0NiIHMf1crQ6p6/xgLmOqD5v2uLSAwuwJLfyOG8xpSizUS8GadFXQKv/bX0GuPAUKTg9PpuZ9LPyqJ9i0ekBybYKvAxRtDSXjrI8h+C0k3G2kPfzWpDHE= root@host2.lab.example.com
      mode: '0700'

  - name: copy boot ISO
    ansible.builtin.shell:
      cmd: "scp  -oStrictHostKeyChecking=no  /var/tmp/rhel-8.6-x86_64-boot.iso ansible_user@{{ fqdn }}:/var/tmp/"
    delegate_to: "{{ groups['hypervisor'][0] }}"
    become: no

  - name: done
    debug:
      msg: done

