- name: image builder service
  hosts: builder
  become: yes
  gather_facts: no
  tasks: 

  # !!! some duplicated in group_vars/builder/main.yml
  # package 'lorax' provides command 'mkksiso'
  # package 'weldr-client' provides command 'composer-cli'
  - name: install image builder packages
    ansible.builtin.dnf:
      name: 
        - cockpit-composer
        - git
        - lorax
        - osbuild-composer
        - weldr-client
      state: latest
    register: r_dnf_builder

  - name: start the server
    ansible.builtin.systemd:
      name: osbuild-composer.socket
      state: started
      enabled: yes

